version: 2
# API
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

      # Backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"